from selenium import webdriver

chrome_path = r"C:\Users\user\Desktop\chromedriver\chromedriver.exe"
driver = webdriver.Chrome(chrome_path)
print("Logging in...")
driver.get("http://hobowars.com")
driver.find_element_by_xpath("""//*[@id="login"]""").click()
driver.find_element_by_xpath("""//*[@id="login"]""").send_keys("purplerober")
driver.find_element_by_xpath("""//*[@id="password"]""").click()
driver.find_element_by_xpath("""//*[@id="password"]""").send_keys("e8iopqas")
driver.find_element_by_xpath("""//*[@id="submitLogin"]""").click()
driver.find_element_by_xpath("""//*[@id="placesList"]/ul/li[11]/a""").click()
print("Initiating War Chamber Fights...")
driver.find_element_by_xpath("""//*[@id="main"]/table[1]/tbody/tr/td[2]/a[10]/i""").click()
driver.find_element_by_xpath("""//*[@id="threadList"]/tbody/tr[3]/td[2]/a""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[1]""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[2]""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[3]""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[4]""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[5]""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[6]""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[7]""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[8]""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[9]""").click()
driver.find_element_by_xpath("""//*[@id="post-content-20649473"]/a[10]""").click()
print("Task complete -- War Chamber Fights")
